apiVersion: v1
kind: Secret
metadata:
  name: argo-ssh-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/emanuelfds/App-Manifest.git