name: Build Docker Image

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      docker_version: ${{ steps.meta.outputs.version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Application
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline

      - name: Display Docker Metadata Output Version
        run: echo "VERSION=${{ steps.meta.outputs.version }}"

  modifygit:
    name: Deploy Application in ArgoCD
    needs: [build-and-push-image]
    runs-on: ubuntu-latest
    
    steps:
      - name: Changing the deployment of git repo
        uses: actions/checkout@v4        
        with:
          ref: 'main'
          repository: 'emanuelfds/App-Manifest'
          token: ${{ secrets.GIT_PAT }}
          persist-credentials: true

      - name: Display Docker Metadata Output Version from build-and-push-image
        run: echo "VERSION=${{ needs.build-and-push-image.outputs.docker_version }}"

      - name: Modifying Tag Image in Deployment
        run: |
          git config user.email ${{ secrets.GIT_EMAIL }}
          git config user.name "${{ vars.GIT_USERNAME }}"
          pwd
          cat ${{ vars.K8S_PATH }}/deployment.yaml
          pwd
          sed -i "s+emanuelfds/app.*+emanuelfds/app:v${{ needs.build-and-push-image.outputs.docker_version }}+g" ${{ vars.K8S_PATH }}/deployment.yaml
          sed -i "s+version:.*+version:v${{ needs.build-and-push-image.outputs.docker_version }}+g" ${{ vars.K8S_PATH }}/deployment.yaml
          cat ${{ vars.K8S_PATH }}/deployment.yaml
          git add .
          git commit -m 'Versão da Aplicação alterada: v${{ needs.build-and-push-image.outputs.docker_version }}'
          git push origin main